[package]
name = "zcash-android-wallet-sdk"
version = "0.0.1"
authors = [
    "Jack Grigg <jack@z.cash>",
    "Kevin Gorham <kevin.gorham@z.cash>",
]
description = "JNI backend for the Android wallet SDK"
publish = false
edition = "2018"

[dependencies]
android_logger = "0.6"
failure = "0.1"
futures = { version = "0.1", optional = true }
grpc = { version = "0.6", optional = true }
hex = "0.3"
jni = { version = "0.13", default-features = false }
log = "0.4"
log-panics = "2.0.0"
protobuf = { version = "2", optional = true }

[dependencies.ff]
git = "https://github.com/str4d/librustzcash.git"
rev = "f3f5338282eeda6d9f5bff69f6930a5473c95925"

[dependencies.pairing]
git = "https://github.com/str4d/librustzcash.git"
rev = "f3f5338282eeda6d9f5bff69f6930a5473c95925"

[dependencies.zcash_client_backend]
git = "https://github.com/str4d/librustzcash.git"
rev = "f3f5338282eeda6d9f5bff69f6930a5473c95925"

[dependencies.zcash_client_sqlite]
git = "https://github.com/str4d/librustzcash.git"
rev = "f3f5338282eeda6d9f5bff69f6930a5473c95925"

[dependencies.zcash_primitives]
git = "https://github.com/str4d/librustzcash.git"
rev = "f3f5338282eeda6d9f5bff69f6930a5473c95925"

[dependencies.zcash_proofs]
git = "https://github.com/str4d/librustzcash.git"
rev = "1cbeac9d593d65938870797fb8dbafa352644d34"

[features]
mainnet = ["zcash_client_sqlite/mainnet"]
updater = ["futures", "grpc", "protobuf"]

[lib]
name = "zcashwalletsdk"
path = "src/main/rust/lib.rs"
crate-type = ["staticlib", "cdylib"]

[[bin]]
name = "update-sapling-tree"
path = "src/main/rust/bin/update_sapling_tree.rs"
required-features = ["updater"]
